export const SELECT_OPTION = 'SELECT_OPTION';
export const CHANGE_TEXTAREA = 'CHANGE_TEXTAREA';
export const CHANGE_OWN_DAYS = 'CHANGE_OWN_DAYS';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';
export const CHANGE_END_DATE = 'CHANGE_END_DATE';
export const CHANGE_RANGE_DAYS = 'CHANGE_RANGE_DAYS';
